# Generated by Django 4.0.6 on 2022-08-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0002_alter_curso_modalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='foto',
            field=models.ImageField(max_length=200, null=True, upload_to='fotos'),
        ),
    ]
