# Generated by Django 4.0.6 on 2022-08-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0003_alter_autor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='foto',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='fotos'),
        ),
    ]
