<<<<<<< HEAD
# Generated by Django 4.0.6 on 2022-08-08 15:16
=======
# Generated by Django 4.0.6 on 2022-08-08 22:06
>>>>>>> 60ffc6789874fbc16bf0d027fa3a8852ffa59f87

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='modalidade',
<<<<<<< HEAD
            field=models.CharField(choices=[('Bacharelado', 'Bacharelado'), ('Licenciatura', 'Licenciatura'), ('Tecnólogo', 'Tecnólogo')], max_length=30),
=======
            field=models.CharField(choices=[('Bacharelado', 'Bacharelado'), ('Licenciatura', 'Licenciatura'), ('Tecnólogo', 'Tecnólogo')], max_length=20),
>>>>>>> 60ffc6789874fbc16bf0d027fa3a8852ffa59f87
        ),
    ]
